=== StudyInParis/geoapplide_xml/grammaire/validation_xml_pivot/obm.dtd
<!ELEMENT root (arrondissement+)>
<!ELEMENT arrondissement (elem*)>
<!ATTLIST arrondissement
          num CDATA #REQUIRED>
<!ELEMENT elem (latitude, longitude, adresse, nom)>
<!ATTLIST elem
          id CDATA #REQUIRED
          type CDATA #REQUIRED>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT nom (#PCDATA)>

=== StudyInParis/geoapplide_xml/XML/fichiers_2xml_pivot/openbeermap_pivot.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE root SYSTEM "../../grammaire/validation_xml_pivot/obm.dtd">
<root>
	<arrondissement num="75001">
		<elem id="0" type="bar">
			<latitude>48.8579257</latitude>
			<longitude>2.3463544</longitude>
			<adresse>Avenue Victoria, St-Germain-l'Auxerrois, 1er</adresse>
			<nom>Les Arènes</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8616362</latitude>
			<longitude>2.3492126</longitude>
			<adresse>Rue Saint-Denis, Les Halles, 1er</adresse>
			<nom>Pop In</nom>
		</elem>
		<elem id="2" type="bar">
			<latitude>48.861037</latitude>
			<longitude>2.3488844</longitude>
			<adresse>Rue Saint-Denis, Les Halles, 1er</adresse>
			<nom>Hall's Beer Tavern</nom>
		</elem>
		<elem id="3" type="bar">
			<latitude>48.8582957</latitude>
			<longitude>2.3474796</longitude>
			<adresse>4, Rue Saint-Denis, St-Germain-l'Auxerrois, 1er</adresse>
			<nom>Le Mayflower</nom>
		</elem>
		<elem id="4" type="bar">
			<latitude>48.8592361</latitude>
			<longitude>2.3476099</longitude>
			<adresse>Rue Saint-Denis, Quartier des Halles, Les Halles, 1er</adresse>
			<nom>Au Trappiste</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75002">
		<elem id="0" type="bar">
			<latitude>48.8693141</latitude>
			<longitude>2.3323713</longitude>
			<adresse>4, Rue Daunou, Gaillon, 2e</adresse>
			<nom>MKP Opéra</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8643869</latitude>
			<longitude>2.3503038</longitude>
			<adresse>Rue Tiquetonne, Sentier, Bonne-Nouvelle, 2e</adresse>
			<nom>Le Havane</nom>
		</elem>
		<elem id="2" type="bar">
			<latitude>48.8678347</latitude>
			<longitude>2.3438681</longitude>
			<adresse>Rue Montmartre, Mail, 2e</adresse>
			<nom>Taverne de la Butte</nom>
		</elem>
		<elem id="3" type="bar">
			<latitude>48.8704075</latitude>
			<longitude>2.3483529</longitude>
			<adresse>Rue Notre-Dame de Recouvrance, Sentier, Bonne-Nouvelle, 2e</adresse>
			<nom>Le Petit Châtelet</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75004">
		<elem id="0" type="bar">
			<latitude>48.8556943</latitude>
			<longitude>2.3595261</longitude>
			<adresse>Rue de Rivoli, St-Gervais, 4e</adresse>
			<nom>Le Comptoir</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8595197</latitude>
			<longitude>2.3519694</longitude>
			<adresse>Place Igor Stravinsky, Beaubourg, St-Merri, 4e</adresse>
			<nom>Le Pantalon</nom>
		</elem>
		<elem id="2" type="bar">
			<latitude>48.8538804</latitude>
			<longitude>2.3682665</longitude>
			<adresse>Rue de la Bastille, Arsenal, 4e</adresse>
			<nom>The Frog and Princess</nom>
		</elem>
		<elem id="3" type="bar">
			<latitude>48.8573507</latitude>
			<longitude>2.3496668</longitude>
			<adresse>Rue de la Coutellerie, Beaubourg, St-Merri, 4e</adresse>
			<nom>La Venus Noire</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75005">
		<elem id="0" type="bar">
			<latitude>48.8449764</latitude>
			<longitude>2.3549028</longitude>
			<adresse>Rue Guy de la Brosse, St-Victor, 5e</adresse>
			<nom>Chez Michel</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8490395</latitude>
			<longitude>2.348557</longitude>
			<adresse>Rue de la Montagne Sainte-Geneviève, Sorbonne, 5e</adresse>
			<nom>Dupont Versailles</nom>
		</elem>
		<elem id="2" type="bar">
			<latitude>48.8525447</latitude>
			<longitude>2.3466628</longitude>
			<adresse>Rue du Petit Pont, Sorbonne, 5e</adresse>
			<nom>L'Alibi</nom>
		</elem>
		<elem id="3" type="bar">
			<latitude>48.850854</latitude>
			<longitude>2.3477158</longitude>
			<adresse>Rue des Anglais, Sorbonne, 5e</adresse>
			<nom>L'Europe</nom>
		</elem>
		<elem id="4" type="bar">
			<latitude>48.8457908</latitude>
			<longitude>2.3539346</longitude>
			<adresse>Rue des Boulangers, St-Victor, 5e</adresse>
			<nom>Le Bistrot des Artistes</nom>
		</elem>
		<elem id="5" type="bar">
			<latitude>48.845275</latitude>
			<longitude>2.3491659</longitude>
			<adresse>45, Rue Descartes, 5e Arrondissement, 5e</adresse>
			<nom>Finnegan's Wake</nom>
		</elem>
		<elem id="6" type="bar">
			<latitude>48.853075</latitude>
			<longitude>2.3455319</longitude>
			<adresse>20, Rue de la Huchette, Ilot Saint-Severin, Sorbonne, 5e</adresse>
			<nom>Mc Brides</nom>
		</elem>
		<elem id="7" type="bar">
			<latitude>48.8423393</latitude>
			<longitude>2.3498473</longitude>
			<adresse>Rue Mouffetard, 5e Arrondissement, 5e</adresse>
			<nom>The Frog and Rosbif</nom>
		</elem>
		<elem id="8" type="bar">
			<latitude>48.8474266</latitude>
			<longitude>2.3471508</longitude>
			<adresse>18, Rue Laplace, Sorbonne, 5e</adresse>
			<nom>Le Vieux Chêne</nom>
		</elem>
		<elem id="9" type="bar">
			<latitude>48.8424716</latitude>
			<longitude>2.3498216</longitude>
			<adresse>Rue Mouffetard, 5e Arrondissement, 5e</adresse>
			<nom>Le Sully</nom>
		</elem>
		<elem id="10" type="bar">
			<latitude>48.8442543</latitude>
			<longitude>2.3498652</longitude>
			<adresse>51, Rue Lacépède, 5e Arrondissement, 5e</adresse>
			<nom>Margen's Pub</nom>
		</elem>
		<elem id="11" type="bar">
			<latitude>48.8430061</latitude>
			<longitude>2.3486843</longitude>
			<adresse>16, Rue du Pot de Fer, Val-de-Grâce, 5e</adresse>
			<nom>Le Calbar</nom>
		</elem>
		<elem id="12" type="bar">
			<latitude>48.8456039</latitude>
			<longitude>2.3547969</longitude>
			<adresse>Place Jussieu, St-Victor, 5e</adresse>
			<nom>Black Mad Crawler</nom>
		</elem>
		<elem id="13" type="bar">
			<latitude>48.8457052</latitude>
			<longitude>2.3419808</longitude>
			<adresse>Rue Royer-Collard, Val-de-Grâce, 5e</adresse>
			<nom>Le Festin Nu</nom>
		</elem>
		<elem id="14" type="bar">
			<latitude>48.8462166</latitude>
			<longitude>2.342933</longitude>
			<adresse>Rue Malebranche, 5e Arrondissement, 5e</adresse>
			<nom>L'Iris</nom>
		</elem>
		<elem id="15" type="bar">
			<latitude>48.848301</latitude>
			<longitude>2.3417712</longitude>
			<adresse>Rue Cujas, Sorbonne, 5e</adresse>
			<nom>Le Troll</nom>
		</elem>
		<elem id="16" type="bar">
			<latitude>48.8451034</latitude>
			<longitude>2.3492463</longitude>
			<adresse>49, Rue Descartes, 5e Arrondissement, 5e</adresse>
			<nom>Le Rota</nom>
		</elem>
		<elem id="17" type="bar">
			<latitude>48.8433232</latitude>
			<longitude>2.3528098</longitude>
			<adresse>Rue de la Clef, Jardin des Plantes, 5e</adresse>
			<nom>Lounge Paradise</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75006">
		<elem id="0" type="bar">
			<latitude>48.8522792</latitude>
			<longitude>2.3345573</longitude>
			<adresse>Rue Princesse, Odéon, 6e</adresse>
			<nom>Le Bouillon St Stef</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8536005</latitude>
			<longitude>2.3428569</longitude>
			<adresse>Rue de l'Hirondelle, Monnaie, 6e</adresse>
			<nom>The Frog at Bercy Village</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75007">
	</arrondissement>
	<arrondissement num="75008">
		<elem id="0" type="bar">
			<latitude>48.8778514</latitude>
			<longitude>2.3157284</longitude>
			<adresse>Rue de Lisbonne, Europe, 8e</adresse>
			<nom>La Caravane</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75009">
		<elem id="0" type="bar">
			<latitude>48.870988</latitude>
			<longitude>2.3449749</longitude>
			<adresse>Boulevard Poissonnière, Sentier, 9e Arrondissement</adresse>
			<nom>James Hetfeeld's Pub</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8713994</latitude>
			<longitude>2.3446987</longitude>
			<adresse>Boulevard Poissonnière, Sentier, 9e Arrondissement</adresse>
			<nom>The Wall</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75010">
		<elem id="0" type="bar">
			<latitude>48.8713202</latitude>
			<longitude>2.365856</longitude>
			<adresse>Quai de Jemmapes, Porte-St-Martin, 10e</adresse>
			<nom>Le chinois</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8703084</latitude>
			<longitude>2.3528255</longitude>
			<adresse>Rue du Faubourg Saint-Denis, Porte-St-Denis, 10e</adresse>
			<nom>Le Dumas</nom>
		</elem>
		<elem id="2" type="bar">
			<latitude>48.8782984</latitude>
			<longitude>2.3583405</longitude>
			<adresse>1, Rue des Deux Gares, St-Vincent-de-Paul, 10e</adresse>
			<nom>Café Leffe</nom>
		</elem>
		<elem id="3" type="bar">
			<latitude>48.8727411</latitude>
			<longitude>2.3545133</longitude>
			<adresse>Rue du Château d'Eau, Porte-St-Denis, 10e</adresse>
			<nom>Le Rivolux</nom>
		</elem>
		<elem id="4" type="bar">
			<latitude>48.8711993</latitude>
			<longitude>2.3697018</longitude>
			<adresse>13, Rue Jacques Louvel-Tessier, Hôpital-St-Louis, 10e</adresse>
			<nom>Le Château d'Eau</nom>
		</elem>
		<elem id="5" type="bar">
			<latitude>48.8746926</latitude>
			<longitude>2.3541936</longitude>
			<adresse>12, Rue de Paradis, Porte-St-Denis, 10e</adresse>
			<nom>Le Triangle</nom>
		</elem>
		<elem id="6" type="bar">
			<latitude>48.8707201</latitude>
			<longitude>2.3498182</longitude>
			<adresse>Rue d'Hauteville, Porte-St-Denis, 10e</adresse>
			<nom>Wos Bar</nom>
		</elem>
		<elem id="7" type="bar">
			<latitude>48.8815009</latitude>
			<longitude>2.3685984</longitude>
			<adresse>200, Quai de Valmy, Hôpital-St-Louis, 10e</adresse>
			<nom>Lêche vin</nom>
		</elem>
	</arrondissement>
	<arrondissement num="75011">
		<elem id="0" type="bar">
			<latitude>48.8648511</latitude>
			<longitude>2.3817815</longitude>
			<adresse>6, Avenue Jean Aicard, St-Ambroise, 11e</adresse>
			<nom>Le Dernier Bar Avant la Fin du Monde</nom>
		</elem>
		<elem id="1" type="bar">
			<latitude>48.8614116</latitude>
			<longitude>2.3675537</longitude>
			<adresse>105, Rue Amelot, St-Ambroise, 11e</adresse>
			<nom>L'antidote</nom>
		</elem>
		<elem id="2" type="bar">
			<latitude>48.8527486</latitude>
			<longitude>2.3889981</longitude>
			<adresse>Rue Alexandre Dumas, Ste-Marguerite, 11e</adresse>
			<nom>Thirsty Mad Cat</nom>
		</elem>
		<elem id="3" type="bar">
			<latitude>48.8553007</latitude>
			<longitude>2.3755708</longitude>
